/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-12-29 下午9:16' with Gradle 2.14.1
 *
 * @author Administrator, @date 16-12-29 下午9:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
